### PR TITLE
add kubernetes support

### PR DESCRIPTION
**Pull request by cristinabuciu**
- add docker files for deploying master and workers
- add yaml files for deploying in Kubernetes
- add logic for start workers on demand and destroy them after the work is done using Kubernetes
- enable metrics using Graphite and Grafana

### CODE REVIEW

**Comment by cristinabuciu** [comment]
@Abiy can you take a look?

**Comment by Abiy** [comment]
Yeah, I am looking at it. I just want to make sure we are not changing existing behavior.

**Comment by Abiy** [comment]
Can you split the README in two separate files 
README.md
KUBERNETES_README.md

**Comment by cristinabuciu** [comment]
> Yeah, I am looking at it. I just want to make sure we are not changing existing behavior.

all changes were made keeping unchanged the existing behaviour

**Comment by mariusioana** [comment]
@Abiy any updates on this one? Would be nice to merge it :)

**Comment by Abiy** [comment]
I merged this PR but the Travis test is failing. Can you take a look?

**Comment by cristinabuciu** [comment]
@Abiy , I will take a look these days

**Pull request merged**
